CREATE TABLE CLIENT (
	CLIENT_ID VARCHAR(36) NOT NULL DEFAULT (UUID()) PRIMARY KEY,
    X_CLIENT_ID VARCHAR(100) NOT NULL,
    X_API_KEY_DEV1 VARCHAR(100),
    X_API_KEY_PROD VARCHAR(100),
    CLIENT_CREATE_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CLIENT_LAST_UPDATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CLIENT_RATE_LIMIT INT,
    CLIENT_ROLE VARCHAR(30)
);

ALTER TABLE CLIENT ADD UNIQUE (X_CLIENT_ID);