CREATE TABLE JOB_APPLICATION (
	JAM_ID VARCHAR(36) NOT NULL DEFAULT (UUID()) PRIMARY KEY,
    JAM_JOB_TITLE VARCHAR(50),
    JAM_COMPANY_NAME VARCHAR(50),
    JAM_URL VARCHAR(150),
    JAM_DESCRIPTION VARCHAR(500),
    JAM_INTERVIEW_PROCESS VARCHAR(500)
);